FROM golang:1.23-bookworm AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /server ./cmd/server

FROM gcr.io/distroless/static-debian12
WORKDIR /
COPY --from=build /server /server
COPY migrations /migrations
ENV ADDR=:8080
ENV MIGRATIONS_DIR=/migrations
EXPOSE 8080
ENTRYPOINT ["/server"]
